name: example-file-upload
on: workflow_dispatch
jobs:
  get_report:
    runs-on: ubuntu-latest
    steps:
      - name: Create Test File
        run: touch test/foo.txt
      - name: Send to Sharepoint
        uses: cringdahl/sharepoint-file-upload-action@v1.2.1
        with:
          file_path: "test/*.txt"
          host_name: 'xinbyte.sharepoint.com'
          site_name: 'OpenWrt'
          upload_path: 'OpenWrt/Test'
          tenant_id: ${{ secrets.SHAREPOINT_TENANT_ID }}
          client_id: ${{ secrets.SHAREPOINT_CLIENT_ID }}
          client_secret: ${{ secrets.SHAREPOINT_CLIENT_SECRET }}