name: example-file-upload
on: workflow_dispatch
jobs:
  get_report:
    runs-on: ubuntu-latest
    steps:
      - name: Create Test File
        run: |
          mkdir test
          echo "hello" >> foo.txt
      - name: 1 Upload SP_UEFI_IMG_GZ to SharePoint
        uses: su-dont/share-point-uploader@v2.1
        with:
          sp_url: https://xinbyte.sharepoint.com/:f:/r/sites/OpenWrt
          sp_username: ${{ secrets.USERNAME }}
          sp_password: ${{ secrets.PASSWORD }}
          sp_folder: /Shared Documents/OpenWrt/Test
          sp_file_name: foo.txt
          file: foo.txt